fix(ssurl): use `percent_decode_str` for `userinfo` encoded data
shadowsocks/shadowsocks-rust pull request #985
Opened 2022-10-25 15:09 UTC by RAX7

Some URLs contain a base64 string with `=` char (e.g: `ss://YWVzLTEyOC1nY206c2hhZG93c29ja3M=@1.2.3.4:8000#tag`) which breaks the `ssurl` tool.

2022-10-25 15:14 UTC, zonyitoo commented
This is impossible. The userinfo has to be encoded with base64 url safe encoding, which is definitely don't have any `=`. `ss://YWVzLTEyOC1nY206c2hhZG93c29ja3M=@1.2.3.4:8000#tag` is not a valid SIP002 URL.

2022-10-25 15:17 UTC, RAX7 commented
@zonyitoo base64 may contain `=` for padding
> = padding characters might be added to make the last encoded block contain four Base64 characters.
> https://en.wikipedia.org/wiki/Base64

2022-10-25 15:21 UTC, zonyitoo commented
You are messing up "base64" and "base64 url safe" encoding.

1. Read the "URL Applications" section in your provided wiki: https://en.wikipedia.org/wiki/Base64#URL_applications
2. RFC4648 base64url: https://datatracker.ietf.org/doc/html/rfc4648#section-5

2022-10-25 15:36 UTC, database64128 commented
Your example is an invalid URL with characters outside the allowed set but not percent encoded. This won't even work with some URL parsers. I don't know how you obtained this "URL", but you should tell whoever generated it to use a proper URL builder, not string concatenation.

2022-10-25 15:37 UTC, RAX7 commented
Oh yes you are right.
> You should make a PR to fix where the URL was generated.

I can't do that, I'm just trying to use [outline](https://getoutline.me/access-keys/8856/) keys and `ssurl` breaks with error.
May I create another PR witch remove all `=` chars from userinfo to make this tool more user friendly?

2022-10-25 15:38 UTC, zonyitoo commented
Well, the code in PR actually trying to decode the userinfo with percent encoding, so the actual example should be: `ss://YWVzLTEyOC1nY206c2hhZG93c29ja3M%3D@1.2.3.4:8000#tag`

2022-10-25 15:42 UTC, zonyitoo commented
> May I create another PR witch remove all `=` chars from userinfo to make this tool more user friendly?

No you should not do that. You may also need to check if there is any characters that are not in the valid base64 url safe character set and try to fix it to fulfill the specification requirement.

You will never be able to compatible all kinds of errors, which is why we need a specification.

But on the otherhand, I noticed that some base64 encoder, such as [the one in Python](https://docs.python.org/3/library/base64.html#base64.urlsafe_b64encode) will still add tailing `=`s for url safe encoding. So I think this PR is still valid for this situation.

2022-10-25 15:45 UTC, database64128 commented
https://github.com/Jigsaw-Code/outline-shadowsocksconfig/blob/master/src/shadowsocks_config.ts#L338

It seems they are indeed using string concatenation. You should also open an issue over there.

2022-10-25 15:50 UTC, zonyitoo commented
```typescript
const userInfo = Base64.encodeURI(`${method.data}:${password.data}`);
```

https://github.com/dankogai/js-base64/blob/68f12dea403e8b0031b09fa5edd0904066fb7ab4/base64.ts#L121-L133

```typescript
const _mkUriSafe = (src: string) => src
    .replace(/=/g, '').replace(/[+\/]/g, (m0) => m0 == '+' ? '-' : '_');

/**
 * converts a UTF-8-encoded string to a Base64 string.
 * @param {boolean} [urlsafe] if `true` make the result URL-safe
 * @returns {string} Base64 string
 */
const encode = (src: string, urlsafe = false) => urlsafe
    ? _mkUriSafe(_encode(src))
    : _encode(src);
/**
 * converts a UTF-8-encoded string to URL-safe Base64 RFC4648 §5.
 * @returns {string} Base64 string
 */
const encodeURI = (src: string) => encode(src, true);
```

So the outline generated URL shouldn't contain any `=`.

2022-10-25 15:53 UTC, RAX7 commented
@zonyitoo the original URL I took [here](https://getoutline.me/access-keys/8856/) and it's: `ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpHIXlCd1BXSDNWYW8=@ak1489.free.www.outline.network:806#www.outline.network%20(canada)`

2022-10-25 15:57 UTC, zonyitoo commented
Interesting, the code in outline-server is Ok but the console is running a different code version.

Please checkout the comments in the review, I am Ok to merge this PR if they are fixed.

2022-10-25 16:23 UTC, RAX7 commented
@zonyitoo, @database64128 I guess they using `outline-shadowsocksconfig` only for desktop client, but not for website
https://github.com/Jigsaw-Code/outline-client/blob/master/package.json#L54

> Please checkout the comments in the review, I am Ok to merge this PR if they are fixed.

Test cases fails on windows with:
```
Error: There is not enough space on the disk. : 'D:\a\_temp\_runner_file_commands\step_summary_7596271d-8edb-440d-9476-a7e3c69f2199'
```

2022-10-25 17:19 UTC, zonyitoo commented
Just ignore the Windows test case.

2022-10-26 01:47 UTC, zonyitoo requested changes

2022-10-26 05:58 UTC, merged